package elaborato.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import elaborato.ricerca.AutomunitoFilter;
import elaborato.ricerca.DisponibilitaComuneFilter;
import elaborato.ricerca.Filter;
import javafx.event.ActionEvent;

public class ComuneController {
	@FXML
	private Button invio_comune;
	@FXML
	private TextField nome_comune;

	private DisponibilitaComuneFilter filtro;

	// Event Listener on Button[#invio_comune].onAction
	@FXML
	public void getcomune_oa(ActionEvent event) {
		// TODO Autogenerated
		DisponibilitaComuneFilter f = new DisponibilitaComuneFilter();
		f.addFilterElement(nome_comune.getText());
		filtro = f;
		System.out.printf("%s", f.getQueryString(null));
		// chiusura
		invio_comune.getScene().getWindow().hide();
	}

	public Filter getfilter() {
		// TODO Auto-generated method stub
		return filtro;
	}
}
