package elaborato.controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import elaborato.DAO.Lingua;
import elaborato.DAO.LinguaDAO;
import elaborato.ricerca.Filter;
import elaborato.ricerca.LinguaFilter;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;
import javafx.scene.control.SelectionMode;

public class LinguaController implements Initializable {
	@FXML
	private Button invio_dati;
	@FXML
	private ListView<Lingua> lingue;
	ObservableList<Lingua> lingua;

	private LinguaFilter filtro;

	// Event Listener on Button[#invio_dati].onAction
	@FXML
	public void getlingue_oa(ActionEvent event) {
		// TODO Autogenerated
		LinguaFilter lf = new LinguaFilter();

		// solo una sola lingua
		// lf.addFilterElement(lingue.getSelectionModel().getSelectedItem());

		// passo piu lingue
		for (Lingua l : lingue.getSelectionModel().getSelectedItems()) {
			lf.addFilterElement(l);
		}

		filtro = lf;
		System.out.printf("%s", filtro.getQueryString("and"));

		invio_dati.getScene().getWindow().hide();
	}

	public Filter getfilter() {
		// TODO Auto-generated method stub
		return filtro;
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		LinguaDAO linguaDAO = new LinguaDAO();

		try {
			this.lingua = FXCollections.observableArrayList(linguaDAO.getAllLingue());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		lingue.setItems(lingua);
		lingue.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
	}
}
