package elaborato;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import elaborato.DAO.Lavoro_svolto;
import elaborato.DAO.LinguaDAO;
import elaborato.DAO.PatenteDAO;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.DatePicker;
import javafx.scene.control.SelectionMode;
import javafx.scene.control.ChoiceBox;

public class aggiornamento_controller {
	@FXML
	private DatePicker data_fine_a;
	@FXML
	private Button update_lavori;
	@FXML
	private DatePicker data_inizio_a;
	@FXML
	private TextField nome_azienda_a;
	@FXML
	private TextField luogo_di_lavoro_a;
	@FXML
	private TextField retribuzione_lorda_giornaliera_a;
	@FXML
	private TextField id_lavoratore_a;
	@FXML
	private ChoiceBox<String> mansioni_svolte_a;
	ObservableList<String> specializzazioni = FXCollections.observableArrayList("bagnino", "barman",
			"istruttore di nuoto", "viticultore", "floricultore");

	// Event Listener on Button[#update_lavori].onAction
	@FXML
	public void update_inserimento_lavoro(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("prova");
		//Lavoro_svolto lavoro_svolto = new Lavoro_svolto( , 0, null, null, null, null, null, null);
		
	}
	
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
		mansioni_svolte_a.setItems(specializzazioni);
	}
}
