package elaborato;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import elaborato.ricerca.AutomunitoFilter;
import elaborato.ricerca.Filter;
import javafx.event.ActionEvent;

import javafx.scene.control.ChoiceBox;

public class automunito_controller implements Initializable{
	@FXML
	private ChoiceBox<Boolean> auto_truefalse;
	@FXML
	private Button invio_dati;

	// Event Listener on Button[#invio_dati].onAction
	@FXML
	public Filter getautomunito_oa(ActionEvent event) {
		// TODO Autogenerated
		//deve ritornare i valori per la listview
		//ritorna un filtro automunito
		AutomunitoFilter af= new AutomunitoFilter();
		af.addFilterElement(auto_truefalse.getSelectionModel().getSelectedItem());
		return af;
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		auto_truefalse.getItems().addAll(true,false);
	}
}
