package elaborato;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class comune_controller {
	@FXML
	private Button invio_comune;
	@FXML
	private TextField nome_comune;

	// Event Listener on Button[#invio_comune].onAction
	@FXML
	public void getcomune_oa(ActionEvent event) {
		// TODO Autogenerated
	}
}
