package elaborato;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class lavoratore_controller {
	@FXML
	private Button invio_dati;
	@FXML
	private TextField nome;
	@FXML
	private TextField cognome;
	@FXML
	private TextField email;

	// Event Listener on Button[#invio_dati].onAction
	@FXML
	public void getlavoratore_oa(ActionEvent event) {
		// TODO Autogenerated
	}
}
