package elaborato;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

public class lingua_controller {
	@FXML
	private Button invio_dati;
	@FXML
	private ListView lingue;

	// Event Listener on Button[#invio_dati].onAction
	@FXML
	public void getlingue_oa(ActionEvent event) {
		// TODO Autogenerated
	}
}
