package elaborato;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class patente_controller {
	@FXML
	private Button invio_dati;

	// Event Listener on Button[#invio_dati].onAction
	@FXML
	public void getpatente_oa(ActionEvent event) {
		// TODO Autogenerated
	}
}
