package elaborato;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import elaborato.ricerca.DisponibilitaComuneFilter;
import elaborato.ricerca.DisponibilitaDataFilter;
import elaborato.ricerca.Filter;
import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;

public class periodo_controller {
	@FXML
	private Button invio_data;
	@FXML
	private DatePicker data_fine;
	@FXML
	private DatePicker data_inizio;
	
	private DisponibilitaDataFilter filtro;

	// Event Listener on Button[#invio_data].onAction
	@FXML
	public void getperiodo_oa(ActionEvent event) { //da completare
		// TODO Autogenerated
		//DisponibilitaDataFilter f= new DisponibilitaDataFilter();
		//f.addFilterElement(data_inizio.getValue(),data_fine.getValue()); //non devo passare due date?
		//filtro = f;
		//System.out.printf("%s",f.getQueryString(null));
		//chiusura
		invio_data.getScene().getWindow().hide();
	}

	public Filter getfilter() {
		// TODO Auto-generated method stub
		return filtro;
	}
}
