package elaborato;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;

public class periodo_controller {
	@FXML
	private Button invio_data;
	@FXML
	private DatePicker data_fine;
	@FXML
	private DatePicker data_inizio;

	// Event Listener on Button[#invio_data].onAction
	@FXML
	public void getperiodo_oa(ActionEvent event) {
		// TODO Autogenerated
	}
}
