package elaborato;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import elaborato.ricerca.*;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ChoiceBox;
import javafx.stage.Modality;
import javafx.stage.Stage;

public class scelta_filtro_controller implements Initializable{
	@FXML
	private ChoiceBox<String> tipi_filtro;
	@FXML
	private Button visiona_finestra_filtro;
	
	//private String controllo_tipo_filtro;
	
	private Filter filtro;
	
	/*private AutomunitoFilter filtro_af;
	private DisponibilitaComuneFilter filtro_dcf;
	private DisponibilitaDataFilter filtro_ddf;
	private LavoratoreFilter filtro_laf;
	private LinguaFilter filtro_lf;
	private PatenteFilter filtro_pf;
	private SpecializzazioneFilter filtro_sf;*/
	
	
	public Filter getfiltro() {
		//inseire i vari switch/if in bae al controllo_tipo_filtro
		return filtro;
	}

	// Event Listener on Button[#visiona_finestra_filtro].onAction
	@FXML
	public void visiona_finestra_filtro_oa(ActionEvent event) throws IOException {
		// TODO Autogenerated
		//in base a che filtro o scelto apro diverse finestre
		Parent root = null;
		Scene scene = null;
		Stage primaryStage = null;
		
		switch(tipi_filtro.getSelectionModel().getSelectedItem()) {
		case "automunito":
			//root = FXMLLoader.load(getClass().getResource("automunito.fxml"));

			/*scene = new Scene(root);
			primaryStage = new Stage();
			primaryStage.setTitle("scegliere_filtro");
			
			// specifico la modalita della nuova finestra
			primaryStage.initModality(Modality.WINDOW_MODAL);
			primaryStage.initOwner(visiona_finestra_filtro.getScene().getWindow()); // specifica il proprietario della nuova finestra;
																		// mi da problemi
			primaryStage.show();*/
			FXMLLoader loader= new FXMLLoader(getClass().getResource("automunito.fxml"));
			primaryStage = new Stage();
			primaryStage.initOwner(visiona_finestra_filtro.getScene().getWindow()); // specifica il proprietario della nuova finestra;
			primaryStage.setScene(new Scene ((Parent) loader.load()));
			
			//wait until the window close
			primaryStage.showAndWait();
			
			automunito_controller am_controller = loader.getController();
			//AutomunitoFilter am_filtro = am_controller.getfilter();
			filtro = am_controller.getfilter();
			System.out.printf("%s\n",filtro.getQueryString(null));
			//am_filtro = am_controller.
			//controllo_tipo_filtro = filtro.getNameFilter();
			//primaryStage.setScene(new Scene(root)); // provare a mettere solo scene
			//primaryStage.show();
			break;
		case "comune":
			root = FXMLLoader.load(getClass().getResource("comune.fxml"));

			scene = new Scene(root);
			primaryStage = new Stage();
			primaryStage.setTitle("scegliere_filtro");
			primaryStage.setScene(scene);
			// specifico la modalita della nuova finestra
			primaryStage.initModality(Modality.WINDOW_MODAL);
			primaryStage.initOwner(visiona_finestra_filtro.getScene().getWindow()); // specifica il proprietario della nuova finestra;
																		// mi da problemi
			primaryStage.show();
			break;
		case "disponibilita":
			 root = FXMLLoader.load(getClass().getResource("periodo.fxml"));

			scene = new Scene(root);
			primaryStage = new Stage();
			primaryStage.setTitle("scegliere_filtro");
			primaryStage.setScene(scene);
			// specifico la modalita della nuova finestra
			primaryStage.initModality(Modality.WINDOW_MODAL);
			primaryStage.initOwner(visiona_finestra_filtro.getScene().getWindow()); // specifica il proprietario della nuova finestra;
																		// mi da problemi
			primaryStage.show();
			break;
		case "lavoratore":
			 root = FXMLLoader.load(getClass().getResource("lavoratore.fxml"));

			scene = new Scene(root);
			primaryStage = new Stage();
			primaryStage.setTitle("scegliere_filtro");
			primaryStage.setScene(scene);
			// specifico la modalita della nuova finestra
			primaryStage.initModality(Modality.WINDOW_MODAL);
			primaryStage.initOwner(visiona_finestra_filtro.getScene().getWindow()); // specifica il proprietario della nuova finestra;
																		// mi da problemi
			primaryStage.show();
			break;
		case "lingua":
			root = FXMLLoader.load(getClass().getResource("lingua.fxml"));

			scene = new Scene(root);
			primaryStage = new Stage();
			primaryStage.setTitle("scegliere_filtro");
			primaryStage.setScene(scene);
			// specifico la modalita della nuova finestra
			primaryStage.initModality(Modality.WINDOW_MODAL);
			primaryStage.initOwner(visiona_finestra_filtro.getScene().getWindow()); // specifica il proprietario della nuova finestra;
																		// mi da problemi
			primaryStage.show();
			break;
		case "patente":
			root = FXMLLoader.load(getClass().getResource("patente.fxml"));

			scene = new Scene(root);
			primaryStage = new Stage();
			primaryStage.setTitle("scegliere_filtro");
			primaryStage.setScene(scene);
			// specifico la modalita della nuova finestra
			primaryStage.initModality(Modality.WINDOW_MODAL);
			primaryStage.initOwner(visiona_finestra_filtro.getScene().getWindow()); // specifica il proprietario della nuova finestra;
																		// mi da problemi
			primaryStage.show();
			break;
		}
		visiona_finestra_filtro.getScene().getWindow().hide();
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		tipi_filtro.getItems().addAll("automunito","comune","disponibilita","lavoratore","lingua","patente"); //dovrei inizializzarlo chiamando getNameFilter
	}
}
